plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.banxu.app'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'cn.banxu.app'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        htmlReport true
        xmlReport true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
